apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-tracking-deployment
spec:
  selector:
    matchLabels:
      app: event-tracking
  template:
    metadata:
      labels:
        app: event-tracking
    spec:
      containers:
        - name: event-tracking
          image: vibesocial/event-tracking:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8081
          resources:
            limits:
              cpu: "1.0"
              memory: "1000Mi"
            requests:
              cpu: "0.75"
              memory: "500Mi"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
            successThreshold: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
