apiVersion: v1
kind: Service
metadata:
  name: event-tracking-service
  namespace: vibe-social
spec:
  type: LoadBalancer
  selector:
    app: event-tracking
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
    - protocol: TCP
      name: grpc
      port: 81
      targetPort: 8081
