apiVersion: v1
kind: Service
metadata:
  name: event-tracking-service
spec:
  selector:
    app: event-tracking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
