info:
  contact:
    email: rm6551@student.uni-lj.si
    name: Rok Mokotar
    url: https://www.linkedin.com/in/mokot/
  description: Event tracking documentation for the social networking app focused
    on sharing vibes.
  title: Event Tracking API Documentation
  version: "1.0"
paths:
  /events:
    get:
      description: get events
      operationId: get-events
      produces:
      - application/json
      responses: {}
      summary: List events
      tags:
      - events
  /health:
    get:
      description: health check
      operationId: health-check
      produces:
      - application/json
      responses: {}
      summary: Health check
      tags:
      - health
  /metrics:
    get:
      description: Prometheus metrics
      operationId: prometheus-metrics
      produces:
      - application/json
      responses: {}
      summary: Prometheus metrics
      tags:
      - metrics
swagger: "2.0"
