info:
  contact:
    email: rm6551@student.uni-lj.si
    name: Rok Mokotar
    url: https://www.linkedin.com/in/mokot/
  description: Event tracking documentation for the social networking app focused
    on sharing vibes.
  title: Event Tracking API Documentation
  version: "1.0"
paths:
  /events:
    get:
      consumes:
      - application/json
      description: get events
      operationId: get-events
      produces:
      - application/json
      responses: {}
      summary: List events
swagger: "2.0"
